### ISSUE TITLE
Not getting incoming message

### ISSUE THREAD

**Issue by pranavpari** [arduino-libraries/ArduinoMqttClient#13] opened 2019-09-15 22:26 UTC
Hello, 
I am not getting an incoming message for a subscribed topic

**Comment by sandeepmistry** [comment] 2019-09-18 13:39
Hi @pranavpari,

Could you please provide more details, such as:
- What board(s) you are using
- Minimal sketch to reproduce the issue
- Broker you are using

**Comment by pranavpari** [comment] 2019-09-19 09:15
I am using arduino uno with esp8266 esp-01 and simply connecting it to CloudMQTT server

**Comment by sandeepmistry** [comment] 2019-10-07 14:02
Please provide the other details requested in https://github.com/arduino-libraries/ArduinoMqttClient/issues/13#issuecomment-532688457.

**Comment by aentinger** [comment] 2020-04-09 06:03
Hi @pranavpari :wave: I'm closing this since there was no feedback from you since 19/09/2019. Please reopen if this is still relevant providing the information outlined in https://github.com/arduino-libraries/ArduinoMqttClient/issues/13#issuecomment-532688457.

**Closed by aentinger** 2020-04-09 06:03 UTC
Labels: waiting for feedback
