### ISSUE TITLE
Connection lost message size > 256

### ISSUE THREAD

**Issue by sebb898** [arduino-libraries/ArduinoMqttClient#20] opened 2019-10-26 18:38 UTC
Hi i have tried to mod the Arduino example  "AWS_IoT_GSM" to be able to get longer message size on MQTT with following code below:

```
void publishMessage(String input) {
  Serial.println("Publishing message");

    bool retained = false;
    int qos = 0; // Have tested with both 0 and 1 
    bool dup = false;


  mqttClient.beginMessage("arduino/outgoing",input.length(),retained,qos,dup);
  mqttClient.print(input);
  mqttClient.endMessage();
}
```

I can send one or two message then i lose connection. But it works fine if i just use
  "mqttClient.beginMessage("arduino/outgoing");"

**Comment by sandeepmistry** [comment] 2019-11-11 21:56
Hi @sebb898,

Could you please provide a full sketch and more detailed steps to reproduce this issue. In particular it's not clear what `input` contains. Thank you.

**Comment by aentinger** [comment] 2020-04-09 06:09
Hi @sebb898 :wave: I'm closing this since there was no feedback from you since 11/11/2019. Please reopen if this is still relevant providing the information requested in https://github.com/arduino-libraries/ArduinoMqttClient/issues/20#issuecomment-552634652 .

**Closed by aentinger** 2020-04-09 06:09 UTC
Labels: waiting for feedback
